
modLoader="javafml"
loaderVersion="[41,)"
license="MIT"
[[mods]]
modId="tameablebeasts"
version="7.0"
displayName="Tameable Beasts"
logoFile="icon.png"
credits="Me"
authors="ModderG"
description='''
Beasts that are tamable duh
'''
[[dependencies.tameablebeasts]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tameablebeasts]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"